#!/bin/sh

set -o errexit
set -o nounset

worker_ready() {
    celery -A vdr_storage_integration inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

flower \
    --app=vdr_storage_integration \
    --broker="${CELERY_BROKER}"