# Generated by Django 3.1.4 on 2021-10-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteSystemSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("highq_base_url", models.URLField()),
                ("aws_access_key_id", models.CharField(max_length=300)),
                ("aws_secret_access_key", models.CharField(max_length=300)),
                ("aws_bucket_name", models.CharField(max_length=300)),
            ],
        ),
    ]
