# Generated by Django 3.1.4 on 2021-10-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remotesystemsettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remotesystemsettings",
            old_name="highq_base_url",
            new_name="remote_system_base_url",
        ),
    ]
