# Generated by Django 3.2 on 2021-11-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("root_folder_name", models.CharField(max_length=1000)),
                ("task_start", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
