# Generated by Django 3.2 on 2021-12-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("line", models.CharField(max_length=1500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.report",
                    ),
                ),
            ],
        ),
    ]
