# Generated by Django 3.2 on 2021-12-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_reportline_related_celery_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportline",
            name="related_celery_task",
        ),
    ]
